{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "pycharm": {
     "is_executing": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET / HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_renderer/react@16.v1_1_2m1576595738.8.6.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_renderer/prop-types@15.v1_1_2m1576595738.7.2.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_renderer/react-dom@16.v1_1_2m1576595738.8.6.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_core_components/highlight.v1_3_1m1576595950.pack.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_html_components/dash_html_components.v1_0_1m1576596177.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_renderer/dash_renderer.v1_1_2m1576595738.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_core_components/dash_core_components.v1_3_1m1576595950.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:49] \"\u001B[37mGET /_dash-component-suites/dash_core_components/plotly-1.v1_3_1m1576595950.50.1.min.js HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:51] \"\u001B[37mGET /_dash-dependencies HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:51] \"\u001B[37mGET /_dash-layout HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:51] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "n_clicks: None\n",
      "new []\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:08:53] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:08:53] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:08:57] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:08:57] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:09] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:09] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:11] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:11] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:14] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:14] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:17] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:17] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:18] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:18] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "n_clicks: 1\n",
      "new []\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:18] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:20] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:20] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:22] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n",
      "127.0.0.1 - - [27/Jul/2021 18:09:22] \"\u001B[37mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "n_clicks: 2\n",
      "new ['k']\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/maxi/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 125, in chart_3d\n",
      "    f = create_figure(deleted_points)\n",
      "  File \"<ipython-input-6-a93f99966855>\", line 50, in create_figure\n",
      "    dfs = dataframe.drop(skip_points)\n",
      "AttributeError: 'list' object has no attribute 'drop'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Jul/2021 18:09:22] \"\u001B[35m\u001B[1mPOST /_dash-update-component HTTP/1.1\u001B[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import plotly.express as px\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import dash\n",
    "from dash.dependencies import Input, Output, State\n",
    "\n",
    "import plotly.graph_objs as go\n",
    "import json\n",
    "\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "\n",
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "app.css.append_css({\n",
    "    \"external_url\": \"https://codepen.io/chriddyp/pen/bWLwgP.css\"\n",
    "})\n",
    "\n",
    "\n",
    "\n",
    "import pandas as pd\n",
    "df = pd.DataFrame(columns=['x_val','z_val','y_val'])\n",
    "df.loc['a'] = [11.313449728149418,0.13039110880256777,0.5386387766748618]\n",
    "df.loc['b'] = [11.321463427315383,0.2360697833061771,1.32441455152796]\n",
    "df.loc['c'] = [10.127132005050942,0.23085014016641864,1.0961116175427044]\n",
    "df.loc['d'] = [11.639819269465233,0.0958798324712593,0.6506370305953094]\n",
    "df.loc['e'] = [8.892696370438149,0.08223988244819926,0.6440321391968353]\n",
    "df.loc['f'] = [6.711586646011124,0.3657515974938044,0]\n",
    "df.loc['g'] = [7.095030650760687,0,0.5723062047617504]\n",
    "df.loc['h'] = [6.4523124528415,0,1.293852184258803]\n",
    "df.loc['i'] = [7.165105300812886,0.4151365420301895,-0.5920674079031845]\n",
    "df.loc['j'] = [7.480703395137295,0.14284429977557123,1.0600936940126982]\n",
    "df.loc['k'] = [5.570775744372319,0,0]\n",
    "df.loc['l'] = [4.358946555449826,0,0]\n",
    "\n",
    "df2 = pd.DataFrame(columns=['x_val','z_val','y_val'])\n",
    "df2.loc['a'] = [9.313449728149418,0.13039110880256777,0.5386387766748618]\n",
    "df2.loc['b'] = [1.321463427315383,0.2360697833061771,1.32441455152796]\n",
    "df2.loc['c'] = [9.127132005050942,0.23085014016641864,1.0961116175427044]\n",
    "df2.loc['d'] = [11.639819269465233,0.0958798324712593,0.56506370305953094]\n",
    "df2.loc['e'] = [0.892696370438149,0.108223988244819926,0.6440321391968353]\n",
    "df2.loc['f'] = [16.711586646011124,0.3657515974938044,0]\n",
    "df2.loc['g'] = [7.095030650760687,0,0.5723062047617504]\n",
    "df2.loc['h'] = [6.4523124528415,0,13.293852184258803]\n",
    "df2.loc['i'] = [17.165105300812886,0.4151365420301895,-0.5920674079031845]\n",
    "df2.loc['j'] = [7.480703395137295,0.14284429977557123,13.0600936940126982]\n",
    "df2.loc['k'] = [5.570775744372319,2,0]\n",
    "df2.loc['l'] = [4.358946555449826,0,3]\n",
    "\n",
    "\n",
    "def create_figure(dataframe, skip_points=[]):\n",
    "    dfs = dataframe.drop(skip_points)\n",
    "    return px.scatter_3d(dfs, x = 'x_val', y = 'y_val', z = 'z_val')\n",
    "f= create_figure(df)\n",
    "d= create_figure(df2)\n",
    "\n",
    "app.layout = html.Div([html.Button('Delete', id='delete'),\n",
    "                    html.Button('Clear Selection', id='clear'),\n",
    "                    html.Button('Procrustes analysis', id='procrustes_analyses'),\n",
    "                    dcc.Graph(id = '3d_scat', figure=f),\n",
    "                    html.Div('selected:'),\n",
    "                    html.Div(id='selected_points'), #, style={'display': 'none'})),\n",
    "                    html.Div('deleted:'),\n",
    "                    html.Div(id='deleted_points'), #, style={'display': 'none'}))\n",
    "                    dcc.Graph(id = '3d_scat_2', figure=d)\n",
    "])\n",
    "\n",
    "@app.callback(Output('deleted_points', 'children'),\n",
    "            [Input('delete', 'n_clicks')],\n",
    "            [State('selected_points', 'children'),\n",
    "            State('deleted_points', 'children')])\n",
    "\n",
    "def delete_points(n_clicks, selected_points, delete_points):\n",
    "    print('n_clicks:',n_clicks)\n",
    "    if selected_points:\n",
    "        selected_points = json.loads(selected_points)\n",
    "    else:\n",
    "        selected_points = []\n",
    "\n",
    "    if delete_points:\n",
    "        deleted_points = json.loads(delete_points)\n",
    "    else:\n",
    "        deleted_points = []\n",
    "    ns = [p['pointNumber'] for p in selected_points]\n",
    "    new_indices = [df.index[n] for n in ns if df.index[n] not in deleted_points]\n",
    "    print('new',new_indices)\n",
    "    deleted_points.extend(new_indices)\n",
    "    return json.dumps(deleted_points)\n",
    "\n",
    "\n",
    "\n",
    "@app.callback(Output('selected_points', 'children'),\n",
    "            [Input('3d_scat', 'clickData'),\n",
    "                Input('deleted_points', 'children'),\n",
    "                Input('clear', 'n_clicks')],\n",
    "            [State('selected_points', 'children')])\n",
    "\n",
    "def select_point(clickData, deleted_points, clear_clicked, selected_points):\n",
    "    ctx = dash.callback_context\n",
    "    ids = [c['prop_id'] for c in ctx.triggered]\n",
    "\n",
    "    if selected_points:\n",
    "        results = json.loads(selected_points)\n",
    "    else:\n",
    "        results = []\n",
    "\n",
    "\n",
    "    if '3d_scat.clickData' in ids:\n",
    "        if clickData:\n",
    "            for p in clickData['points']:\n",
    "                if p not in results:\n",
    "                    results.append(p)\n",
    "    if 'deleted_points.children' in ids or  'clear.n_clicks' in ids:\n",
    "        results = []\n",
    "    results = json.dumps(results)\n",
    "    return results\n",
    "\n",
    "@app.callback(Output('3d_scat', 'figure'),\n",
    "            [Input('selected_points', 'children'),\n",
    "            Input('deleted_points', 'children')],\n",
    "            [State('deleted_points', 'children')])\n",
    "\n",
    "\n",
    "def chart_3d( selected_points, deleted_points_input, deleted_points_state):\n",
    "    global f\n",
    "    global d\n",
    "    deleted_points = json.loads(deleted_points_state) if deleted_points_state else []\n",
    "    f = create_figure(deleted_points)\n",
    "    d = create_figure(deleted_points)\n",
    "\n",
    "    selected_points = json.loads(selected_points) if selected_points else []\n",
    "    if selected_points:\n",
    "        f.add_trace(\n",
    "            go.Scatter3d(\n",
    "                mode='markers',\n",
    "                x=[p['x'] for p in selected_points],\n",
    "                y=[p['y'] for p in selected_points],\n",
    "                z=[p['z'] for p in selected_points],\n",
    "                marker=dict(\n",
    "                    color='red',\n",
    "                    size=5,\n",
    "                    line=dict(\n",
    "                        color='red',\n",
    "                        width=2\n",
    "                    )\n",
    "                ),\n",
    "                showlegend=False\n",
    "            )\n",
    "        )\n",
    "\n",
    "        d.add_trace(\n",
    "            go.Scatter3d(\n",
    "                mode='markers',\n",
    "                x=[p['x'] for p in selected_points],\n",
    "                y=[p['y'] for p in selected_points],\n",
    "                z=[p['z'] for p in selected_points],\n",
    "                marker=dict(\n",
    "                    color='red',\n",
    "                    size=5,\n",
    "                    line=dict(\n",
    "                        color='red',\n",
    "                        width=2\n",
    "                    )\n",
    "                ),\n",
    "                showlegend=False\n",
    "            )\n",
    "        )\n",
    "\n",
    "    return f ,d\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}